### PR TITLE
Remove old connection to pool if the refresh metadata remove the broker

### PR DESCRIPTION
**Pull request by BDeus**
New case here.
When a server down, the Metadatacache do not drop old connection to server.

### CODE REVIEW

**Comment by EranOfer** [comment]
we may be needed to make another state to the connections.
we want the connection to always being connected if it is a leader.

if not we don't need to maintain a connection all the time get on demand for make new metadata request .

i don't think you want to remove the server if it fails.
you just want to move the connection to on demand state.

what do you think?

**Comment by BDeus** [comment]
MetadataResponse do not response with a broker id that has been shutdown or unreachable.
I think we need to remove connection with unreachable broker but i agree we need to manage topic with leader = -1

**Comment by BDeus** [comment]
we can put connection in failure state instead of just drop it.
We also need to manage the huge among of throw exception when a server fail

**Comment by EranOfer** [comment]
hi,
I'm not in the office so i will be back on thursday and look on it.

**Comment by BDeus** [comment]
ok no problem i will begin to manage this too

**Comment by BDeus** [comment]
i currently work on KafkaTcpSocket and KafkaMetadataProvider
there is an issue with metadata when a broker isn't available. The metadata message will be stuck in the write queue of the KafkaTcpSocket until exception was throw (if we have a max retry with high number the wait can be very long).
I don't understand why we need to query all brokers node for metadata, the message will be the same on all brokers.
I planned to modify that to query the first node available

**Comment by EranOfer** [comment]
It's looking good but missing a new UnitTest:
"RefreshTopic Metadata" can call the remove connection.
does it need to be the last connection?

We can make the MetadataProvider.Get use Task.any and using the first MetadataResponse can help make the respone faster

Something else that i need to add:
The protocol Gateway needs to recover UpsertConnectionToBrokerConnectionIndex

**Comment by EranOfer** [comment]
I think the approach we've took to this issue is wrong. Let's redefine what we are trying to solve.

If I'm understanding correctly, we want to prevent a situation that an idle broker connection takes up resources (either because there is no activity on the connection or the broker is down). 
In this case, removing the connection or moving it to the `_defaultConnectionIndex` is not the right solution, and we may need a smarter optimization - like reading from the connection only if we've sent a request that didn't return yet. The juggling of connection between lists seems unhealthy.

So in this case, I'm going to close this PR, and let's open an issue to discuss a different solution.
Regarding the other problem with the `SendAsync` timeout - please open a different issue for that.
Another thing - please open all issues and PRs [here](https://github.com/gigya/KafkaNetClient), the main respository.

**Comment by BDeus** [comment]
ok we will discuss of this on main repo in different issue

**Pull request closed without merging**
